# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [6]:
arr2 = np.zeros(10)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [7]:
arr3 = np.arange(10,49)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [8]:
arr3.shape

(39,)

5. Print the type of the previous array in question 3

In [10]:
print(arr3.dtype)

int32


6. Print the numpy version and the configuration


In [11]:
print(np.__version__)
print(np.__config__)

1.18.1
<module 'numpy.__config__' from 'C:\\Users\\DELL\\anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


7. Print the dimension of the array in question 3


In [12]:
print(arr3.ndim)

1


8. Create a boolean array with all the True values

In [16]:
arr8 = np.arange(7)
boolean_arr = arr8 < 10
boolean_arr

array([ True,  True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [22]:
arr9 = np.array([[np.arange(1,4)],
               [np.arange(4,7)]])
arr9

array([[[1, 2, 3]],

       [[4, 5, 6]]])

10. Create a three dimensional array



In [23]:
arr10 = np.array([[np.arange(1,4)],
               [np.ones(3)],
                 [np.zeros(3)]])
arr10

array([[[1., 2., 3.]],

       [[1., 1., 1.]],

       [[0., 0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [40]:
arr11 = arr3[::-1]
arr11

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [42]:
arr12 = np.zeros(10)
arr12[4] = 1
arr12

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [43]:
arr13 = np.eye(3)
arr13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [47]:
arr = np.array([1,2,3,4,5])
arr14 = np.array(arr, dtype=float)
arr14

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [51]:
arr1 = np.array([[1.,2.,3.],
                 [4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],
                 [7.,2.,12.]])
arr15 = arr1 * arr2
arr15

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [53]:
arr1 = np.array([[1.,2.,3.],
                 [4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],
                 [7.,2.,12.]])
arr16 = arr1 >= arr2
arr16

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [58]:
arr17 = np.arange(10)
arr17[np.arange(10) % 2 != 0]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [61]:
arr18 = arr17[np.arange(10) % 2 != 0] = -1
arr17

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [63]:
arr = np.arange(10)
arr19 = arr[4:8] = 12
arr19, arr

(12, array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9]))

20. Create a 2d array with 1 on the border and 0 inside

In [67]:
arr20 = np.eye(2,2)
arr20

array([[1., 0.],
       [0., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [69]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr2d[1:2,1:2] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [74]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [76]:
arr23 = np.arange(10).reshape(2,5)
arr23[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [79]:
arr24 = np.arange(10).reshape(2,5)
arr24[1,1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [82]:
arr25 = np.arange(10).reshape(2,5)
arr25[:,2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [100]:
arr26 = np.array(np.random.rand(10,10) * 8, dtype = 'int32')
print(arr26)
print('Min value in array is:',arr26.min())
print('Max value in array is:',arr26.max())

[[7 4 6 1 5 0 7 0 4 6]
 [0 7 0 0 0 0 2 0 0 3]
 [6 7 2 5 7 3 0 6 7 4]
 [1 5 4 3 3 0 5 7 6 3]
 [5 3 2 4 7 4 5 4 4 4]
 [4 4 7 7 5 0 4 3 5 2]
 [5 5 6 4 4 4 0 3 7 0]
 [3 5 6 7 3 5 1 6 1 5]
 [2 1 3 4 4 2 0 6 0 1]
 [4 1 4 5 5 2 0 2 2 6]]
Min value in array is: 0
Max value in array is: 7


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


40. Generate a matrix of 20 random values and find its cumulative sum