In [8]:
import numpy as np

In [2]:
# now lets do this with a numpy array
array_to_square = np.arange(0, 100000)


# and time using a vectorized operation
%timeit array_to_square ** 2

94 µs ± 2.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
arry = np.array([1,2,3,4,5,6])
arry

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arry)

numpy.ndarray

In [6]:
np.size(arry)

6

In [7]:
arry.dtype

dtype('int32')

In [8]:
test_array = np.array([11,22,55,66,77.7])
test_array

array([11. , 22. , 55. , 66. , 77.7])

In [9]:
arry.ndim

1

In [10]:
test_array.ndim

1

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.shape(np.arange(100))

(100,)

In [18]:
np.arange(1,101,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [27]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [37]:
a = [1,2,3,4,5,6,7]
np.asarray(a)

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
b = [1,2,3,4,5,6]
np.array(a)

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
a,b

([1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6])

In [48]:
np.array([np.ones(5)],
         [np.zeros(5)])

TypeError: data type not understood

In [51]:
int_arry = np.array([100,200,300,400,550])
int_arry.dtype

dtype('int32')

In [52]:
int_arry.astype(np.float)

array([100., 200., 300., 400., 550.])

In [56]:
a1 = np.arange(1, 11)
a1 * 9

array([ 9, 18, 27, 36, 45, 54, 63, 72, 81, 90])

In [59]:
a1[0], a1[2]

(1, 3)

In [60]:
arr2d = np.array([[1,2,3,4,5,6], [11,22,33,44,55,66]])
arr2d

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [62]:
print("======================================================")
# reshaping a 2darray to 3darray
arr2d = np.arange(64).reshape(8,8)

print(arr2d)

arr3d = arr2d.reshape(2,4,8)  #(depth, rows,columns)
arr3d

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [64]:
arr3d.shape

(2, 4, 8)

In [70]:
arr4d = arr3d.reshape(4,4,4)
arr4d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [71]:
newarry = np.arange(25).reshape(5,5)
newarry

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
#light blue
newarry[0:4,1:2]

array([[ 1],
       [ 6],
       [11],
       [16]])

In [73]:
#dark blue
newarry[0:2,3:5]

array([[3, 4],
       [8, 9]])

In [74]:
#orange
newarry[2:3,1:4]

array([[11, 12, 13]])

In [75]:
#yellow
newarry[1:5,0:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [76]:
#green
newarry[3:5,2:5]

array([[17, 18, 19],
       [22, 23, 24]])

In [80]:
newarry[-1,-3]

22

In [1]:
import PIL

In [2]:
print(PIL.__version__)

7.0.0


In [5]:
from PIL import Image

In [1]:
image = Image.open('InShot_20201018_220818154.jpg')
image

NameError: name 'Image' is not defined

In [7]:
type(image)

PIL.JpegImagePlugin.JpegImageFile

In [10]:
imgarray = np.asarray(image)
imgarray

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [11]:
imgarray.shape

(1920, 2560, 3)

In [13]:
imgarray.ravel().shape

(14745600,)

In [15]:
from matplotlib import image
from matplotlib import pyplot

In [17]:
img = image.imread('InShot_20201018_220818154.jpg')
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [18]:
img.dtype

dtype('uint8')

In [19]:
img.shape

(1920, 2560, 3)

In [2]:
pyplot.imshow(img)

NameError: name 'pyplot' is not defined

In [3]:
newimg = Image.open('InShot_20201018_220818154.jpg')
newimg = newimg.convert('L')
gr_img = newimg.save('Gray.png')
pyplot.imshow(np.array(Image.open('Gray.png').convert()))


NameError: name 'Image' is not defined